<template>
    <section class="w-50 m-auto mt-4">
    <h3>LITTLE HISTORY</h3>
    <p>LOREM IPSUM DOLOR SIT AMET CONSECTETUR ADIPISICING ELIT. EVENIET, ELIGENDI CONSEQUATUR EA QUASI REPREHENDERIT ODIO ACCUSANTIUM ASPERIORES TEMPORA! PERSPICIATIS, ILLUM IURE UT ASPERIORES QUI REICIENDIS EXERCITATIONEM VERITATIS INCIDUNT NOBIS FUGA!</p>
    
    </section>


</template>


<script>
export default{
    name: "Caption"
}
</script>